# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'fontingAwesome' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'FontAwesomeKit', '~> 2.2'
pod 'CWStatusBarNotification', '~> 2.3'
  # Pods for fontingAwesome

end
